version: '3.2'

services:
  prometheus:
    image: prom/prometheus:v2.33.4
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true

  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    hostname: node-exporter
    ports:
      - 9100:9100
    restart: unless-stopped

  grafana:
      image: grafana/grafana:8.4.3
      container_name: grafana
      hostname: grafana
      restart: unless-stopped
      ports:
          - 3000:3000

